#!/bin/bash
# 
# Generate pod spesc from PLACEMENT spec
# Usage:   PLACEMENT=./..  me 
#

if [ -z ${PLACEMENT} ]; then
    echo Usage: PLACEMENT=...  `basename "$0"`
    exit
fi
source $PLACEMENT

function create-pod-spec {
    export IDX=$(echo $1 | awk -F "-" '{ print $1}')
    export ROLE=$(echo $s | awk -F "-" '{ print$2}')
    export WORKER=$(echo $s | awk -F "-" '{ print$3}')
    echo IDX=$IDX ROLE=$ROLE WORKER=$WORKER
    envsubst < templates/$ROLE-$WORKER.json.template > ./generated/$IDX-$ROLE-$WORKER.json

}

rm -fr ./generated
mkdir ./generated

for s in ${HWOL_SERVERS[@]}; do
    create-pod-spec $s
done
for s in ${HWOL_CLIENTS[@]}; do
    create-pod-spec $s
done

for s in ${NO_SERVERS[@]}; do
    create-pod-spec $s
done
for s in ${NO_CLIENTS[@]}; do
    create-pod-spec $s
done

rm *client*.json *server*.json 2>/dev/null
cp ./generated/* .

